In [2]:
import pandas as pd
pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",sep=";")

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [3]:
data=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",sep=";")

In [4]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [9]:
data.shape

(1599, 12)

In [6]:
from sklearn.model_selection import train_test_split``
train,test=train_test_split(data)

In [7]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
309,7.4,0.29,0.38,1.7,0.062,9.0,30.0,0.99680,3.41,0.53,9.5,6
846,6.4,0.64,0.21,1.8,0.081,14.0,31.0,0.99689,3.59,0.66,9.8,5
1459,7.9,0.20,0.35,1.7,0.054,7.0,15.0,0.99458,3.32,0.80,11.9,7
1549,7.4,0.36,0.30,1.8,0.074,17.0,24.0,0.99419,3.24,0.70,11.4,8
1385,8.0,0.81,0.25,3.4,0.076,34.0,85.0,0.99668,3.19,0.42,9.2,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1592,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
590,9.0,0.45,0.49,2.6,0.084,21.0,75.0,0.99870,3.35,0.57,9.7,5
255,8.0,0.57,0.23,3.2,0.073,17.0,119.0,0.99675,3.26,0.57,9.3,5
689,8.1,0.38,0.48,1.8,0.157,5.0,17.0,0.99760,3.30,1.05,9.4,5
1337,6.0,0.50,0.00,1.4,0.057,15.0,26.0,0.99448,3.36,0.45,9.5,5

In [8]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1330,7.4,0.600,0.26,2.1,0.083,17.0,91.0,0.99616,3.29,0.56,9.8,6
66,7.5,0.520,0.11,1.5,0.079,11.0,39.0,0.99680,3.42,0.58,9.6,5
223,8.6,0.645,0.25,2.0,0.083,8.0,28.0,0.99815,3.28,0.60,10.0,6
50,8.8,0.660,0.26,1.7,0.074,4.0,23.0,0.99710,3.15,0.74,9.2,5
767,7.5,0.600,0.32,2.7,0.103,13.0,98.0,0.99938,3.45,0.62,9.5,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1535,7.0,0.550,0.13,2.2,0.075,15.0,35.0,0.99590,3.36,0.59,9.7,6
778,8.3,0.430,0.30,3.4,0.079,7.0,34.0,0.99788,3.36,0.61,10.5,5
686,7.1,0.650,0.18,1.8,0.070,13.0,40.0,0.99700,3.44,0.60,9.1,5
1547,6.3,0.600,0.10,1.6,0.048,12.0,26.0,0.99306,3.55,0.51,12.1,5
742,6.5,0.615,0.00,1.9,0.065,9.0,18.0,0.99720,3.46,0.65,9.2,5

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import ElasticNet

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,accuracy_score,roc_auc_score
from sklearn.model_selection import  train_test_split

In [11]:
X_train=train.drop(["quality"],axis=1)
X_test=test.drop(["quality"],axis=1)
    
y_train=train[["quality"]]
y_test=test[["quality"]]

In [12]:
rf=RandomForestClassifier()
rf.fit(X_train, y_train)

C:\Users\aariz\AppData\Local\Temp/ipykernel_21884/4040854503.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)

RandomForestClassifier()

In [13]:
X_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
1330,7.4,0.600,0.26,2.1,0.083,17.0,91.0,0.99616,3.29,0.56,9.8
66,7.5,0.520,0.11,1.5,0.079,11.0,39.0,0.99680,3.42,0.58,9.6
223,8.6,0.645,0.25,2.0,0.083,8.0,28.0,0.99815,3.28,0.60,10.0
50,8.8,0.660,0.26,1.7,0.074,4.0,23.0,0.99710,3.15,0.74,9.2
767,7.5,0.600,0.32,2.7,0.103,13.0,98.0,0.99938,3.45,0.62,9.5
...,...,...,...,...,...,...,...,...,...,...,...
1535,7.0,0.550,0.13,2.2,0.075,15.0,35.0,0.99590,3.36,0.59,9.7
778,8.3,0.430,0.30,3.4,0.079,7.0,34.0,0.99788,3.36,0.61,10.5
686,7.1,0.650,0.18,1.8,0.070,13.0,40.0,0.99700,3.44,0.60,9.1
1547,6.3,0.600,0.10,1.6,0.048,12.0,26.0,0.99306,3.55,0.51,12.1
742,6.5,0.615,0.00,1.9,0.065,9.0,18.0,0.99720,3.46,0.65,9.2

In [14]:
pred_prob=rf.predict_proba(X_test)

In [15]:
roc_auc_score=roc_auc_score(y_test,pred_prob,multi_class='ovr')

In [16]:
roc_auc_score

0.8485635903025025